# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  solution: './APITempDIO/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration:  'Release'

steps:

- task: UseDotNet@2
  displayName: 'Install .NEt SDK'
  inputs:
    packageType: 'sdk'
    version: '8.x'

- script: dotnet restore $(solution)
  displayName: 'Run a one-line script'

- script: dotnet build $(solution) --configuration $(buildConfiguration)
  displayName: 'Build solution'

- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
